# action.yml
name: 'Hello World2'
description: 'Greet someone and record the time'
inputs:
  repo:
    description: 'github repository ex: (heumlabs/blahblah)'
    required: true
  branch:
    description: '현재 origin 에 push 한 배포용 브랜치명'
    required: true
  title:
    description: '슬랙 공지용 메시지 title'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
    - ${{ inputs.title }}
