# action.yml
name: 'deploy dashboard'
description: '배포 자동화 및 이력 관리'
inputs:
  repo:
    description: 'github repository ex: heumlabs/blahblah'
    required: true
  branch:
    description: 'release branch 명 ex: release,'
    required: false
  target:
    description: 'pull request 에서 머지될 base branch 명 ex: main, staging..'
    required: false
  title:
    description: '슬랙 공지용 메시지 title'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
    - ${{ inputs.target }}
    - ${{ inputs.title }}
