on: [push]

jobs:
  hello_world_job2:
    runs-on: ubuntu-latest
    steps:
      - name: deploy action
        id: hello2
        uses: heumlabs/deploy-actions@v6
        with:
          repo: heumlabs/deploy-actions
          branch: release
          title: r2m
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello2.outputs.time }}"
