on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: deploy action
        uses: heumlabs/deploy-actions@v1
        with:
          repo: heumlabs/deploy-actions
          title: r2m
